[package]
name = "kirito_contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.11.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }

[dev-dependencies]
snforge_std = "0.44.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
# See more config options https://foundry-rs.github.io/starknet-foundry/appendix/snforge-toml.html