[package]
name = "kirito_contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.3"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
# See more config options https://foundry-rs.github.io/starknet-foundry/appendix/snforge-toml.html